name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          auto-activate-base: false
          channels: conda-forge

      - name: Install dependencies
        run: mamba install ipython=7 flake8

      - name: Install xeus-python-shell
        run: pip install .

      - name: Test import
        run: python -c "import xeus_python_shell"

      - name: Test flake8
        run: flake8 xeus_python_shell --ignore=E501,W504,W503
